import type { ShortcutCommand } from './types';

const SWITCH_TABS: ShortcutCommand[] = ([1, 2, 3, 4, 5, 6, 7, 8, 9] as const).map((n) => ({
    id: `switchTab${n}`,
    label: `Switch to Tab ${n}`,
    section: 'tabs',
    defaultKeys: `Mod+${n}`,
    when: 'always',
    settingsKey: `switchTab${n}`,
    configurable: true,
}));

const FILE_MANAGER: ShortcutCommand[] = [
    { id: 'fmCopy', label: 'Copy', section: 'files', defaultKeys: 'Mod+C', when: 'files', settingsKey: 'fmCopy', configurable: true },
    { id: 'fmCut', label: 'Cut', section: 'files', defaultKeys: 'Mod+X', when: 'files', settingsKey: 'fmCut', configurable: true },
    { id: 'fmPaste', label: 'Paste', section: 'files', defaultKeys: 'Mod+V', when: 'files', settingsKey: 'fmPaste', configurable: true },
    { id: 'fmSelectAll', label: 'Select All', section: 'files', defaultKeys: 'Mod+A', when: 'files', settingsKey: 'fmSelectAll', configurable: true },
    { id: 'fmRename', label: 'Rename', section: 'files', defaultKeys: 'F2', when: 'files', settingsKey: 'fmRename', configurable: true },
    { id: 'fmDelete', label: 'Delete', section: 'files', defaultKeys: 'Delete', when: 'files', settingsKey: 'fmDelete', configurable: true },
    { id: 'fmEditPath', label: 'Edit Path', section: 'files', defaultKeys: 'Mod+L', when: 'files', settingsKey: 'fmEditPath', configurable: true },
    { id: 'fmSearch', label: 'Search', section: 'files', defaultKeys: 'Mod+F', when: 'files', settingsKey: 'fmSearch', configurable: true },
    { id: 'fmOpen', label: 'Open Selection', section: 'files', defaultKeys: 'Enter', when: 'files', settingsKey: 'fmOpen', configurable: true },
    { id: 'fmUp', label: 'Go Up', section: 'files', defaultKeys: 'Alt+Up', when: 'files', settingsKey: 'fmUp', configurable: true },
    { id: 'fmBack', label: 'Go Back', section: 'files', defaultKeys: 'Alt+Left', when: 'files', settingsKey: 'fmBack', configurable: true },
    { id: 'fmForward', label: 'Go Forward', section: 'files', defaultKeys: 'Alt+Right', when: 'files', settingsKey: 'fmForward', configurable: true },

    { id: 'fmListView', label: 'List View', section: 'files', defaultKeys: 'Mod+Shift+1', when: 'files', settingsKey: 'fmListView', configurable: true },
    { id: 'fmGridView', label: 'Grid View', section: 'files', defaultKeys: 'Mod+Shift+2', when: 'files', settingsKey: 'fmGridView', configurable: true },
    { id: 'fmHidden', label: 'Show/Hide Hidden Files', section: 'files', defaultKeys: 'Mod+H', when: 'files', settingsKey: 'fmHidden', configurable: true },
    { id: 'fmBookmark', label: 'Bookmark Current Location', section: 'files', defaultKeys: 'Mod+D', when: 'files', settingsKey: 'fmBookmark', configurable: true },
    { id: 'fmRefresh', label: 'Refresh View', section: 'files', defaultKeys: 'F5', when: 'files', settingsKey: 'fmRefresh', configurable: true },
];

/**
 * Zync commands. PTY chords (Ctrl+/) are not listed here.
 *
 * `when: 'app'` — skip while xterm is focused under shell-first (Ctrl+T/W/F/N).
 * `when: 'always'` — still work in a terminal (sidebar, palette, AI, Shift chords, tab switch).
 * `settings.keybindings` overrides `defaultKeys` when `settingsKey` is set.
 */
export const SHORTCUT_CATALOG: readonly ShortcutCommand[] = [
    {
        id: 'openNewConnection',
        label: 'New Connection',
        section: 'global',
        defaultKeys: 'Mod+N',
        when: 'app',
        settingsKey: 'openNewConnection',
        configurable: true,
    },
    {
        id: 'toggleSidebar',
        label: 'Toggle Sidebar',
        section: 'global',
        defaultKeys: 'Mod+B',
        when: 'always',
        settingsKey: 'toggleSidebar',
        configurable: true,
    },
    {
        id: 'newLocalTerminal',
        label: 'Local Terminal',
        section: 'global',
        defaultKeys: 'Mod+T',
        when: 'app',
        settingsKey: 'newLocalTerminal',
        configurable: true,
    },
    {
        id: 'toggleSettings',
        label: 'Settings',
        section: 'global',
        defaultKeys: 'Mod+,',
        when: 'always',
        settingsKey: 'toggleSettings',
        configurable: true,
    },
    {
        id: 'commandPalette',
        label: 'Command Palette',
        section: 'global',
        defaultKeys: 'Mod+P',
        when: 'always',
        settingsKey: 'commandPalette',
        configurable: true,
    },
    {
        id: 'commandPaletteMode',
        label: 'Command Palette (commands)',
        section: 'hidden',
        defaultKeys: 'Mod+Shift+P',
        when: 'always',
        configurable: false,
    },
    {
        id: 'aiCommandBar',
        label: 'AI Command Bar',
        section: 'global',
        defaultKeys: 'Mod+I',
        when: 'always',
        settingsKey: 'aiCommandBar',
        configurable: true,
    },
    {
        id: 'newHostTerminal',
        label: 'New Terminal (Current Host)',
        section: 'tabs',
        defaultKeys: 'Mod+Shift+T',
        when: 'always',
        settingsKey: 'newHostTerminal',
        configurable: true,
    },
    {
        id: 'closeTab',
        label: 'Close Tab',
        section: 'tabs',
        defaultKeys: 'Mod+W',
        when: 'app',
        settingsKey: 'closeTab',
        configurable: true,
    },
    {
        id: 'closeTerminalTab',
        label: 'Close Terminal Tab',
        section: 'terminal',
        defaultKeys: 'Mod+Shift+W',
        when: 'always',
        settingsKey: 'closeTerminalTab',
        configurable: true,
    },
    {
        id: 'splitPanes',
        label: 'Split focused pane',
        section: 'terminal',
        defaultKeys: 'Ctrl+Shift+ArrowRight',
        extraKeys: ['Ctrl+Shift+ArrowLeft', 'Ctrl+Shift+ArrowUp', 'Ctrl+Shift+ArrowDown'],
        when: 'always',
        settingsKey: 'splitPanes',
        configurable: true,
    },
    {
        id: 'focusSplitPane',
        label: 'Focus pane in direction',
        section: 'terminal',
        defaultKeys: 'Ctrl+Alt+ArrowRight',
        extraKeys: ['Ctrl+Alt+ArrowLeft', 'Ctrl+Alt+ArrowUp', 'Ctrl+Alt+ArrowDown'],
        when: 'always',
        settingsKey: 'focusSplitPane',
        configurable: true,
    },
    {
        id: 'switchTabNext',
        label: 'Next Tab',
        section: 'tabs',
        defaultKeys: 'Ctrl+Tab',
        when: 'always',
        settingsKey: 'switchTabNext',
        configurable: true,
    },
    {
        id: 'switchTabPrev',
        label: 'Previous Tab',
        section: 'tabs',
        defaultKeys: 'Ctrl+Shift+Tab',
        when: 'always',
        settingsKey: 'switchTabPrev',
        configurable: true,
    },
    ...SWITCH_TABS,
    {
        id: 'termCopy',
        label: 'Copy',
        section: 'terminal',
        defaultKeys: 'Mod+Shift+C',
        when: 'always',
        settingsKey: 'termCopy',
        configurable: true,
    },
    {
        id: 'termPaste',
        label: 'Paste',
        section: 'terminal',
        defaultKeys: 'Mod+Shift+V',
        when: 'always',
        settingsKey: 'termPaste',
        configurable: true,
    },
    {
        id: 'termFind',
        label: 'Find',
        section: 'terminal',
        defaultKeys: 'Mod+F',
        when: 'app',
        settingsKey: 'termFind',
        configurable: true,
    },
    {
        id: 'zoomIn',
        label: 'Zoom In',
        section: 'view',
        defaultKeys: 'Mod+=',
        extraKeys: ['Mod+Plus'],
        when: 'app',
        settingsKey: 'zoomIn',
        configurable: true,
    },
    {
        id: 'zoomOut',
        label: 'Zoom Out',
        section: 'view',
        defaultKeys: 'Mod+-',
        when: 'app',
        settingsKey: 'zoomOut',
        configurable: true,
    },
    {
        id: 'filesFeature',
        label: 'Files',
        section: 'hidden',
        defaultKeys: 'Ctrl+Shift+F',
        when: 'always',
        configurable: false,
    },
    {
        id: 'tunnelsFeature',
        label: 'Port Forwarding',
        section: 'hidden',
        defaultKeys: 'Ctrl+Shift+N',
        when: 'always',
        configurable: false,
    },
    {
        id: 'snippetsFeature',
        label: 'Snippets',
        section: 'hidden',
        defaultKeys: 'Ctrl+Shift+S',
        extraKeys: ['Ctrl+Shift+`', 'Ctrl+Shift+~'],
        when: 'always',
        configurable: false,
    },
    {
        id: 'dashboardFeature',
        label: 'Dashboard',
        section: 'hidden',
        defaultKeys: 'Ctrl+Shift+D',
        when: 'always',
        configurable: false,
    },
    ...FILE_MANAGER,
];

export const SHORTCUT_SECTIONS: Array<{ id: ShortcutCommand['section']; title: string }> = [
    { id: 'global', title: 'Global Shortcuts' },
    { id: 'files', title: 'File Manager' },
    { id: 'tabs', title: 'Tabs' },
    { id: 'terminal', title: 'Terminal (Active)' },
    { id: 'view', title: 'View' },
];

export function catalogBySection(section: ShortcutCommand['section']): ShortcutCommand[] {
    return SHORTCUT_CATALOG.filter((row) => row.section === section && row.configurable);
}
